ark:
  container_name: ark
  image: turzam/ark:1.3-dev
  environment:
    - SESSIONNAME=Ark Clux
    - SERVERMAP=TheIsland
    - SERVERPASSWORD="1978" 
    - ADMINPASSWORD=clux1978
    - BACKUPONSTART=1
    - UPDATEONSTART=1
    - TZ=Europe/Paris
    - GID=1000
    - UID=1000
  volumes:
    - /my/path/to/ark:/volume1/ArkServer
  ports:
   - 7778:7778/udp
   - 7778:7778
   - 27015:27015/udp
   - 27015:27015
   - 32330:32330
